package frc.robot.sensors.Vision.MLVision;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.WaitCommand;
import frc.lib.drive.DriveSubsystem;
import frc.robot.subsystems.intake.IntakeSubsystem;

public class DriveToNoteCommand extends Command{
    private DriveSubsystem driveSubsystem;
    private MLVision mlVision;
    Command autoDrive = null;
    private IntakeSubsystem intakeSubsystem;

    public DriveToNoteCommand(DriveSubsystem driveSubsystem, MLVision mlVision, IntakeSubsystem intakeSubsystem){
        this.driveSubsystem = driveSubsystem;
        this.mlVision = mlVision;
        this.intakeSubsystem = intakeSubsystem;
    }

    @Override
    public void end(boolean interrupted) {
    }

    @Override
    public void execute() {
        System.out.println("qfoqewhfo");
    }

    @Override
    public void initialize() {
        autoDrive = new WaitCommand(2);
        // autoDrive = driveSubsystem.autoGeneratedPath(()->mlVision.getClosestNotePos(), ()->intakeSubsystem.hasNote()).until(()->intakeSubsystem.hasNote());
        autoDrive.schedule();
    }

    @Override
    public boolean isFinished() {
        return intakeSubsystem.hasNote();
    }
}
